### ISSUE TITLE
Name of scan is not preserved on export option

### ISSUE THREAD

**Issue by kurtsylint** [nicpenning/Nessus-ES#10]
Consider the following change (works for me) in order to preserve the "vanity name" of the scan in the exported files.
Line 303
$exportFileName = Join-Path $Nessus_File_Download_Location $($($convertedTime | Get-Date -Format yyyy_MM_dd).ToString()+"-$($_.name)"+"-$scanId$($Export_Custom_Extended_File_Name_Attribute).nessus")

**Comment by nicpenning** [comment]
Good idea,  I will see what you are accomplishing here and see how it checks out. Thanks for posting!
